In [1]:
import numpy as np

In [2]:
a=[5,2,7,4,1]

In [3]:
a

[5, 2, 7, 4, 1]

In [4]:
#Converting a list into an array
v = np.array(a)
v

array([5, 2, 7, 4, 1])

In [5]:
print(v)

[5 2 7 4 1]


In [6]:
type(v)

numpy.ndarray

In [7]:
#Directly create an array
v = np.array([5,2,7,4,1])
v

array([5, 2, 7, 4, 1])

In [8]:
#Create a Matrix
v = np.array([[5,2,7],[1,4,8],[11,15,25]])

In [9]:
v

array([[ 5,  2,  7],
       [ 1,  4,  8],
       [11, 15, 25]])

In [10]:
print(v)

[[ 5  2  7]
 [ 1  4  8]
 [11 15 25]]


In [11]:
# To know the rows and columns of a matrix
v.shape

(3, 3)

In [12]:
v1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [13]:
v1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
print(v1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
#Matrix Multiplication
mul = np.matmul(v,v1)
mul

array([[ 62,  76,  90],
       [ 73,  86,  99],
       [246, 297, 348]])

In [16]:
#Dot matrix [Dot matrix and Matmul are the same]
d = np.dot(v,v1)

In [17]:
d

array([[ 62,  76,  90],
       [ 73,  86,  99],
       [246, 297, 348]])

In [18]:
v+v1

array([[ 6,  4, 10],
       [ 5,  9, 14],
       [18, 23, 34]])

In [19]:
v-v1

array([[ 4,  0,  4],
       [-3, -1,  2],
       [ 4,  7, 16]])

In [20]:
v*v1

array([[  5,   4,  21],
       [  4,  20,  48],
       [ 77, 120, 225]])

In [21]:
v/v1

array([[5.        , 1.        , 2.33333333],
       [0.25      , 0.8       , 1.33333333],
       [1.57142857, 1.875     , 2.77777778]])

In [22]:
v**v1

array([[          5,           4,         343],
       [          1,        1024,      262144],
       [   19487171, -1732076671,   766306777]], dtype=int32)

In [23]:
v%v1

array([[0, 0, 1],
       [1, 4, 2],
       [4, 7, 7]], dtype=int32)

In [24]:
v//v1

array([[5, 1, 2],
       [0, 0, 1],
       [1, 1, 2]], dtype=int32)

In [25]:
#mean of matrix
np.sum(v)


78

In [26]:
np.add(v,v1)

array([[ 6,  4, 10],
       [ 5,  9, 14],
       [18, 23, 34]])

In [27]:
v+v1 #np.add(v,v1) same

array([[ 6,  4, 10],
       [ 5,  9, 14],
       [18, 23, 34]])

In [28]:
np.subtract(v,v1)#v-v1

array([[ 4,  0,  4],
       [-3, -1,  2],
       [ 4,  7, 16]])

In [29]:
print(np.mean(v))

8.666666666666666


In [30]:
print(np.mean(v1))

5.0


In [31]:
print(round(np.mean(v)))

9


In [32]:
#max
print(np.max(v))

25


In [33]:
print(np.max(v1))

9


In [34]:
#min
print(np.min(v))

1


In [35]:
#print(np.min(v1))
print('min of v',np.min(v),'min of v1',np.min(v1))

min of v 1 min of v1 1


In [36]:
#median
print(np.median(v))
print(np.median(v1))

7.0
5.0


In [37]:
v

array([[ 5,  2,  7],
       [ 1,  4,  8],
       [11, 15, 25]])

In [38]:
v[0]

array([5, 2, 7])

In [39]:
v[1]

array([1, 4, 8])

In [40]:
v1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
v1[1]

array([4, 5, 6])

In [42]:
v[0:1]

array([[5, 2, 7]])

In [43]:
row_v = v[0]
row_v

array([5, 2, 7])

In [44]:
np.max(row_v)

7

In [45]:
#for column
v[:,0]

array([ 5,  1, 11])

In [46]:
v[:,1]

array([ 2,  4, 15])

In [47]:
col_v = v[:,0]

In [48]:
col_v

array([ 5,  1, 11])

In [49]:
np.max(col_v)

11

In [50]:
#Transpose of matrix
v.T

array([[ 5,  1, 11],
       [ 2,  4, 15],
       [ 7,  8, 25]])

In [51]:
#Standard Diviation
print('\n',np.std(v))
print('\n',np.std(v1))


 7.102425250887506

 2.581988897471611


In [52]:
#Square root of the entire matrix
np.sqrt(v)

array([[2.23606798, 1.41421356, 2.64575131],
       [1.        , 2.        , 2.82842712],
       [3.31662479, 3.87298335, 5.        ]])

In [53]:
np.sqrt(v1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [54]:
#creation of Sparse Matrix
#Creating a 5*5 zero matrix
a=np.zeros([5,5])

In [55]:
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [56]:
a.shape

(5, 5)

In [57]:
a = np.ones([5,5])
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [58]:
a.dtype

dtype('float64')

In [59]:
type(a)

numpy.ndarray

In [60]:
#Identity matrix of order 3
a = [1,1,1]
v = np.diag(a)

In [61]:
v

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [62]:
v.shape

(3, 3)

In [63]:
c = np.identity(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [64]:
# not identity but just example
b = [1,2,3,4,5]
v = np.diag(b)
v

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [68]:
#Reshape
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [69]:
a.shape

(2, 5)

In [70]:
a_rshp = a.reshape(5,2)

In [71]:
a_rshp

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [72]:
a_trans = a.T

In [74]:
a_trans

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [75]:
#Flattening: Horizontal Flattening
a_flat = a.flatten()
a_flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
a_flat.shape

(10,)

In [77]:
#Vertical Flattening
a_ver_flat = a.reshape(-1,1)
a_ver_flat

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [78]:
a_ver_flat.shape

(10, 1)

In [81]:
#range function 
a = list(range(1,10))
a

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [82]:
a = list(range(2,11,2))

In [83]:
a

[2, 4, 6, 8, 10]

In [84]:
#arange keyword/ command :-- arange - array range
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [85]:
a = np.arange(1,11,2)
a

array([1, 3, 5, 7, 9])

In [86]:
#linspace - prints number in equal spaces.It has three arguments/Parameters.
v = np.linspace(0,3,10)
v

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [87]:
v = np.linspace(0,5,20)
v

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [89]:
v = np.linspace(0,1)
v

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [90]:
# random numbe generation
#Creating a 5*5 random number matrix:
v = np.random.randn(5,5)

In [91]:
v

array([[-0.048895  , -1.16231901,  0.17213975,  0.36544786, -1.47657329],
       [ 0.96468033, -0.03506307,  0.30176774,  0.06714271, -0.04781997],
       [ 0.29443373, -2.80028715, -0.62565466,  0.20242433, -0.0212188 ],
       [ 1.50032649, -0.28008359, -0.48920368, -0.62004696,  0.74036533],
       [ 1.25443537,  0.31464417, -1.43173765, -1.04756213,  1.07798703]])

In [92]:
v = np.random.rand(5,5)

In [93]:
v

array([[0.42167408, 0.83352162, 0.45959048, 0.69235316, 0.83396267],
       [0.44260113, 0.73216201, 0.45840242, 0.82927846, 0.22164887],
       [0.06303301, 0.34727818, 0.15203344, 0.48286663, 0.37560513],
       [0.97866705, 0.7320681 , 0.95504456, 0.79704782, 0.43821555],
       [0.18896251, 0.72813257, 0.850098  , 0.59551941, 0.98052125]])

In [95]:
v = np.random.rand(10,3)
v
                  

array([[0.2018668 , 0.48845659, 0.84067023],
       [0.19939638, 0.38778123, 0.85546685],
       [0.97273697, 0.85693296, 0.62002829],
       [0.38878105, 0.67429259, 0.93561549],
       [0.64755498, 0.09122036, 0.50248884],
       [0.73422263, 0.2344365 , 0.87568764],
       [0.17050008, 0.31404124, 0.12895146],
       [0.97288561, 0.16451428, 0.51147401],
       [0.66861495, 0.80854496, 0.85273189],
       [0.78254075, 0.74139167, 0.68705506]])

In [118]:
#Creating a random number matrix using only integer values:
v = np.random.randint(10,size=(5,5))
v

array([[9, 1, 3, 3, 2],
       [2, 7, 4, 1, 3],
       [1, 8, 7, 4, 7],
       [3, 2, 6, 1, 3],
       [5, 8, 7, 0, 5]])

In [97]:
v = np.random.randint(1,11,size=(5,5))
v

array([[ 2,  8,  2,  4,  3],
       [ 7,  7,  1,  7,  5],
       [10,  9,  1, 10,  1],
       [ 5,  8,  6,  7,  9],
       [ 2,  8,  6,  1,  3]])

In [98]:
v = np.random.randint(2,size=(5,5))
v

array([[0, 1, 1, 1, 0],
       [1, 0, 0, 1, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 1, 1],
       [0, 1, 1, 0, 1]])

In [99]:
v = np.random.randint(2,size=(3,5))
v

array([[1, 1, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 1, 1, 1, 0]])

In [119]:
v = np.random.randint(1,10,size=(5,5))
v

array([[1, 6, 9, 5, 4],
       [7, 5, 3, 4, 2],
       [5, 4, 4, 5, 2],
       [9, 4, 8, 9, 3],
       [3, 6, 2, 5, 8]])

In [103]:
#v = np.random.randint(-1,-2,size=(5,5))
#v  =========== Error

In [114]:
#function example
def mat():
    n=[]
    v= np.array([5,2,7,4,1])
    v=list(v)
    for x in v:
        if x%2==1:
            n.append(x)
    print(n)
mat()

[5, 7, 1]


In [120]:
v

array([[1, 6, 9, 5, 4],
       [7, 5, 3, 4, 2],
       [5, 4, 4, 5, 2],
       [9, 4, 8, 9, 3],
       [3, 6, 2, 5, 8]])

In [121]:
#Access rown in array
v[1]

array([7, 5, 3, 4, 2])

In [122]:
v[4]

array([3, 6, 2, 5, 8])

In [123]:
#Accessing a single element in an array
v[4][4]

8

In [124]:
v[4,4]

8

In [125]:
v[2,2]#alternative for the above code

4

In [126]:
v[0][1]

6

In [127]:
v

array([[1, 6, 9, 5, 4],
       [7, 5, 3, 4, 2],
       [5, 4, 4, 5, 2],
       [9, 4, 8, 9, 3],
       [3, 6, 2, 5, 8]])

In [128]:
#Accessing of a column
v[0:,1]

array([6, 5, 4, 4, 6])

In [129]:
v[2:,4]

array([2, 3, 8])

In [130]:
v[0:,0]

array([1, 7, 5, 9, 3])

In [131]:
v[:,]

array([[1, 6, 9, 5, 4],
       [7, 5, 3, 4, 2],
       [5, 4, 4, 5, 2],
       [9, 4, 8, 9, 3],
       [3, 6, 2, 5, 8]])

In [135]:
v[:,2].reshape(-1,1)

array([[9],
       [3],
       [4],
       [8],
       [2]])

In [136]:
v[:2,2].reshape(-1,1)

array([[9],
       [3]])

In [137]:
v[:3,2].reshape(-1,1)

array([[9],
       [3],
       [4]])

In [138]:
a = v[0:,2]

In [139]:
a.T

array([9, 3, 4, 8, 2])

In [141]:
a = v[0:,2]
a.reshape(-1,1)

array([[9],
       [3],
       [4],
       [8],
       [2]])

In [142]:
c = v[:,1]
c

array([6, 5, 4, 4, 6])

In [143]:
c= list(c)

In [144]:
c.pop()

6

In [145]:
c

[6, 5, 4, 4]